apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: Tempo
    orgId: 1

datasources:
  - name: Prometheus
    uid: lumina-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: lumina-tempo

  - name: Tempo
    uid: lumina-tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: false
    jsonData:
      tracesToMetrics:
        datasourceUid: lumina-prometheus
        spanStartTimeShift: -5m
        spanEndTimeShift: 5m
        tags:
          - key: service.name
            value: service_name
      serviceMap:
        datasourceUid: lumina-prometheus
      nodeGraph:
        enabled: true
